# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4063ce8db4300b7ca79e6c89bb301840d57c9f2b8f51de84e20d4be0f36d84d2ce9d3b07e84ae7d324853dedcb481e5de7318676ce3be0c9ebf7b980be7ed57e

test:
  secret_key_base: a425b18847b9edee21f6abbc15028b2af4af85e31835b6e6194774aec0a9a66bd160ebdccb8532d6733bd10d4802d59852b4898158e2a03ecb7993f6b5e256bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
